/**
 * Index Manager
 * An example of index manager application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Hit } from './hit';

export interface IndexSearchResult { 
    index: string;
    query: string;
    hits: Array<Hit>;
    currentPage: number;
    totalPages: number;
    pageSize: number;
    totalHits: number;
    maxHits: boolean;
}