# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master", "gae17-micronaut-lae5" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./src/webapp/index-manager
    - name: Install Angular CLI
      run: npm install --location=global @angular/cli
    - name: Install Dependencies
      run: npm install
    - name: Build production
      run: ng build --configuration production
      working-directory: ./src/webapp/index-manager

  
